### ISSUE TITLE
Set up build process

### ISSUE THREAD

**Issue by davidnguyen11** [3BenLee/training-zone-calculator#2]
- Set up ts configuration for build directory by setting value for attribute `outDir`
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "esModuleInterop": true,
    "target": "es2015",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "src/types/*"]
    }
  },
  "include": [
    "src/**/*"
  ]
}
```
- Register the build script to `package.json`

**Note**: To test it, try to create the `index.ts` file in `src/` and then run the build script (`npm run build`) to see it worked or not.

**Comment by 3BenLee** [comment]
Thanks for the help!
